name: Terraform Destroy

on:
  workflow_dispatch:  # Trigger manually from GitHub UI

jobs:
  destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    environment: prod  # Requires manual approval if environment protection is set

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="region=us-east-1"

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
