name: Terraform Destroy

on:
  workflow_dispatch:  # This allows manual trigger from GitHub Actions UI

jobs:
  terraform-destroy-plan:
    name: Terraform Destroy Plan
    runs-on: ubuntu-latest
    environment: prod  # optional, you can require approval here too

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init \
                            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
                            -backend-config="key=terraform.tfstate" \
                            -backend-config="region=us-east-1"

      - name: Terraform Destroy Plan
        run: terraform plan -destroy -out=tfdestroyplan

      - name: Upload Destroy Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfdestroyplan
          path: tfdestroyplan

  terraform-destroy-apply:
    name: Terraform Destroy Apply
    runs-on: ubuntu-latest
    needs: terraform-destroy-plan
    environment: prod  # manual approval required

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Download Destroy Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfdestroyplan
          path: .

      - name: Terraform Destroy
        run: terraform apply -auto-approve tfdestroyplan
